In [1]:
import pandas as pd
import numpy as py
import os
import glob
import matplotlib.pyplot as plt

In [2]:
pd.set_option('max_columns',None)
pd.set_option('max_rows',1000)

In [3]:
df_call_record1 = pd.read_csv('call_record_details_1641204004902.csv')

/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py:3331: DtypeWarning: Columns (17) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
df_call_record1.columns

Index(['sid', 'status', 'phone_no', 'start_time', 'ringing_time', 'duration',
       'caller_id', 'dail_time', 'pick_time', 'end_time', 'telco_code',
       'telco_text', 'recording_url', 'bot_failed', 'chaturl',
       'call_direction', 'billing_minutes', 'company_id', 'insertedDate',
       'updatedDate'],
      dtype='object')

In [5]:
df_call_record1['phone_number'] = df_call_record1['phone_no'].apply(lambda x: int(str(x)[-10:]))
df_call_record1['pick_time'] = pd.to_datetime(df_call_record1['pick_time'],errors='coerce')

In [6]:
df_call_record1.status.value_counts()

not_answered    334857
answered        151710
failed           89593
Name: status, dtype: int64

In [7]:
df_call_record1['hod_of_voicebot_connected'] = pd.to_datetime(df_call_record1.start_time).dt.hour
df_call_record1['date_called'] = pd.to_datetime(df_call_record1.start_time).dt.date
df_call_record1['dom_of_voicebot_connected'] = pd.to_datetime(df_call_record1.start_time).dt.day
df_call_record1['dow_of_voicebot_connected'] = pd.to_datetime(df_call_record1.start_time).dt.dayofweek
df_call_record1['date_time_connected'] = pd.to_datetime(df_call_record1.start_time)

In [8]:
import datetime
#df_call_record['pickup_time_hour_of_the_day'] = df_call_record['pick_time'].apply(lambda x: datetime.time.strftime("%H", x) if x != 'NaN' else '0')

df_call_record1['pickup_time_hour_of_the_day'] = pd.to_datetime(df_call_record1.pick_time).dt.hour

In [9]:
df_call_record1['voicebot_triggered'] = df_call_record1['status'].apply(lambda x: '1' if x != '' else '0')
df_call_record1['voicebot_connected'] = df_call_record1['status'].apply(lambda x: '1' if x == 'answered' else '0')

In [10]:
df_call_record1

,sid,status,phone_no,start_time,ringing_time,duration,caller_id,dail_time,pick_time,end_time,telco_code,telco_text,recording_url,bot_failed,chaturl,call_direction,billing_minutes,company_id,insertedDate,updatedDate,phone_number,hod_of_voicebot_connected,date_called,dom_of_voicebot_connected,dow_of_voicebot_connected,date_time_connected,pickup_time_hour_of_the_day,voicebot_triggered,voicebot_connected
0,8ca57ce22d16469792d032954c8e2104,answered,919844481461,2021-09-08T17:33:36.838,0.0,4.0,918068983636,2021-09-08T17:33:36.838,2021-09-08 17:33:36.588,2021-09-08T17:33:39.963,16,Normal Clearing,https://yellowmessenger.blob.core.windows.net/...,False,https://app.yellowmessenger.com/#/public/messa...,inbound,1.0,NaN,2021-09-08T12:03:47.604Z,2021-09-08T12:03:47.604Z,9844481461,17,2021-09-08,8,2,2021-09-08 17:33:36.838,17.0,1,1
1,92ba02ee97464e2c991b225a28de217d,answered,919818381771,2021-09-08T17:33:19.495,6.0,16.0,918068983636,2021-09-08T17:33:19.495,2021-09-08 17:33:28.083,2021-09-08T17:33:43.703,16,Normal Clearing,https://yellowmessenger.blob.core.windows.net/...,False,https://app.yellowmessenger.com/#/public/messa...,outbound,1.0,NaN,2021-09-08T12:03:47.772Z,2021-09-08T12:03:47.772Z,9818381771,17,2021-09-08,8,2,2021-09-08 17:33:19.495,17.0,1,1
2,048c0dc1c6c340d5b5c1d31b5444f8ea,not_answered,919908486774,2021-09-08T17:33:09.688,27.0,0.0,918068983636,2021-09-08T17:33:09.688,NaT,2021-09-08T17:33:39.339,19,"User alerting, no answer",NaN,False,https://app.yellowmessenger.com/#/public/messa...,outbound,0.0,NaN,2021-09-08T12:03:48.432Z,2021-09-08T12:03:48.432Z,9908486774,17,2021-09-08,8,2,2021-09-08 17:33:09.688,NaN,1,0
3,23133ea472634710850d5bf8867f6656,not_answered,919311852510,2021-09-08T17:33:12.090,28.0,0.0,918068983636,2021-09-08T17:33:12.090,NaT,2021-09-08T17:33:41.808,17,User busy,NaN,False,https://app.yellowmessenger.com/#/public/messa...,outbound,0.0,NaN,2021-09-08T12:03:47.675Z,2021-09-08T12:03:47.675Z,9311852510,17,2021-09-08,8,2,2021-09-08 17:33:12.090,NaN,1,0
4,2918d96bea6149f3b482bda701e6faa4,answered,919991207863,2021-09-08T17:33:09.489,13.0,15.0,918068983636,2021-09-08T17:33:09.489,2021-09-08 17:33:25.127,2021-09-08T17:33:39.872,16,Normal Clearing,https://yellowmessenger.blob.core.windows.net/...,False,https://app.yellowmessenger.com/#/public/messa...,outbound,1.0,NaN,2021-09-08T12:03:47.747Z,2021-09-08T12:03:47.747Z,9991207863,17,2021-09-08,8,2,2021-09-08 17:33:09.489,17.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576155,40df08f0390046f48620babac890f8e4,answered,916201901687,2021-12-19T13:25:24.991,0.0,1.0,918068988518,2021-12-19T13:25:24.991,2021-12-19 13:25:24.738,2021-12-19T13:25:25.062,131,Connect Timeout,NaN,True,https://app.yellowmessenger.com/#/public/messa...,inbound,0.0,NaN,2021-12-19T07:55:25.628Z,2021-12-19T07:55:25.628Z,6201901687,13,2021-12-19,19,6,2021-12-19 13:25:24.991,13.0,1,1
576156,f5c0108a116649b997a13b4cd0ae9079,answered,919985221617,2021-12-30T15:52:04.046,3.0,6.0,918068983636,2021-12-30T15:52:04.046,2021-12-30 15:52:09.860,2021-12-30T15:52:15.664,16,Normal Clearing,https://yellowmessenger.blob.core.windows.net/...,False,https://app.yellowmessenger.com/#/public/messa...,outbound,1.0,NaN,2021-12-30T10:22:19.167Z,2021-12-30T10:22:19.167Z,9985221617,15,2021-12-30,30,3,2021-12-30 15:52:04.046,15.0,1,1
576157,25107195cee041af8048052832449a57,answered,919910224095,2021-12-31T13:47:25.579,0.0,5.0,918068988518,2021-12-31T13:47:25.579,2021-12-31 13:47:25.319,2021-12-31T13:47:30.247,16,Normal Clearing,https://yellowmessenger.blob.core.windows.net/...,False,https://app.yellowmessenger.com/#/public/messa...,inbound,1.0,NaN,2021-12-31T08:17:33.777Z,2021-12-31T08:17:33.778Z,9910224095,13,2021-12-31,31,4,2021-12-31 13:47:25.579,13.0,1,1
576158,d8f7fa9a6ac24c9eb4199b624c212ffe,answered,919959248941,2022-01-01T12:54:32.469,0.0,5.0,918068988519,2022-01-01T12:54:32.469,2022-01-01 12:54:32.219,2022-01-01T12:54:36.675,16,Normal Clearing,https://yellowmessenger.blob.core.windows.net/...,False,https://app.yellowmessenger.com/#/public/messa...,inbound,1.0,NaN,2022-01-01T07:24:40.115Z,2022-01-01T07:24:40.115Z,9959248941,12,2022-01-01,1,5,2022-01-01 12:54:32.469,12.0,1,1
576159,368f8cc33def442f8bc615169013b953,answered,919910224095,2022-01-01T12:56:12.360,0.0,3.0,918068988518,2022-01-01T12:56:12.360,2022-01-01 12:56:12.124,2022-01-01T12:56:15.066,16,Normal Clearing,https://yellowmessenger.blob.core.windows.net/...,False,https://app.yellowmessenger.com/#/public/messa...,inbound,1.0,NaN,2022-01-01T07:26:18.457Z,2022-01-01T07:26:18.457Z,9910224095,12,2022-01-01,1,5,2022-01-01 12:56:12.360,12.0,1,1

In [11]:
df_call_record1 = df_call_record1.rename(columns={'ringing_time': 'duration_of_voicebot_ringing','duration': 'duration_of_voicebot_connected','date_called':'date'})

In [12]:
df_call_record11 = df_call_record1[["phone_number", "date", "voicebot_triggered","voicebot_connected","duration_of_voicebot_connected","hod_of_voicebot_connected","dow_of_voicebot_connected","dom_of_voicebot_connected"]]

In [13]:
df_call_record11

,phone_number,date,voicebot_triggered,voicebot_connected,duration_of_voicebot_connected,hod_of_voicebot_connected,dow_of_voicebot_connected,dom_of_voicebot_connected
0,9844481461,2021-09-08,1,1,4.0,17,2,8
1,9818381771,2021-09-08,1,1,16.0,17,2,8
2,9908486774,2021-09-08,1,0,0.0,17,2,8
3,9311852510,2021-09-08,1,0,0.0,17,2,8
4,9991207863,2021-09-08,1,1,15.0,17,2,8
...,...,...,...,...,...,...,...,...
576155,6201901687,2021-12-19,1,1,1.0,13,6,19
576156,9985221617,2021-12-30,1,1,6.0,15,3,30
576157,9910224095,2021-12-31,1,1,5.0,13,4,31
576158,9959248941,2022-01-01,1,1,5.0,12,5,1
576159,9910224095,2022-01-01,1,1,3.0,12,5,1

# 2nd part

In [14]:
df_call_record2 = pd.read_csv('report_20225910_020135.csv')

In [15]:
df_call_record2

,full_name,phone_number,language,due_amount,paid_flag,payment_date,call triggered date,call_comp_flag,flow_type,stage_code,stage_code_fol,call_status,sts,stage,followup_stage,call duration,main_seq_no,main_ans_seq,main_no_ans_seq,follow_seq_no,follow_ans_seq,follow_no_ans_seq,time stamp,company_name
0,Bablu Pashwan,8528846901,english,1484.0,no,NaN,21/12/2021,no,main,RNR,NaN,BUSY,BUSY,NaN,NaN,0,1,0,1,0,0,0,2021-12-21 17:01:38,Zestmoney
1,Pushpendra Singh,8769132151,english,2719.0,no,NaN,21/12/2021,no,main,RNR,NaN,BUSY,BUSY,NaN,NaN,0,1,0,1,0,0,0,2021-12-21 17:01:39,Zestmoney
2,Pankaj Sharma,9414604647,english,3954.0,no,NaN,21/12/2021,no,main,RNR,NaN,BUSY,BUSY,NaN,NaN,0,1,0,1,0,0,0,2021-12-21 17:01:41,Zestmoney
3,Hitesh Chhotubhai,9099463658,english,1731.0,no,NaN,21/12/2021,no,main,RNR,NaN,BUSY,BUSY,NaN,NaN,0,1,0,1,0,0,0,2021-12-21 17:01:47,Zestmoney
4,Pramod Ghaghretiya,9879874368,english,2349.0,no,NaN,21/12/2021,no,main,RNR,NaN,BUSY,BUSY,NaN,NaN,0,1,0,1,0,0,0,2021-12-21 17:01:50,Zestmoney
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22505,Aabid Khan,9991716345,english,3588.0,no,NaN,20/12/2021,no,main,DSCN,NaN,ANSWERED,ANSWERED,repeat:initial_message,NaN,43,15,8,7,0,0,0,2021-12-20 17:15:11,Zestmoney
22506,Ankit Pal,8299537878,english,15711.0,no,NaN,20/12/2021,no,main,DSCN,NaN,ANSWERED,ANSWERED,repeat:initial_message,NaN,51,13,11,2,0,0,0,2021-12-20 17:15:18,Zestmoney
22507,Mohd Imroz,7419003969,english,5469.0,no,NaN,20/12/2021,no,main,CLBK,NaN,ANSWERED,ANSWERED,busy,NaN,57,13,7,6,0,0,0,2021-12-20 17:15:25,Zestmoney
22508,Shiv Datt,7906796524,english,5686.0,no,NaN,20/12/2021,no,main,DSCN,NaN,ANSWERED,ANSWERED,repeat:initial_message,NaN,56,11,10,1,0,0,0,2021-12-20 17:15:33,Zestmoney
22509,Shyam Sunder,9616412840,english,15083.0,no,NaN,20/12/2021,no,main,DSCN,NaN,ANSWERED,ANSWERED,ask_emi_pay_today,NaN,114,16,10,6,0,0,0,2021-12-20 17:16:01,Zestmoney

In [16]:
df_call_record2 = df_call_record2.rename(columns={'time stamp': 'start_time', 'call_status':'status','call duration': 'call_duration'})

In [17]:
df_call_record2['phone_number'] = df_call_record2['phone_number'].apply(lambda x: int(str(x)[-10:]))

In [18]:
df_call_record2.status.value_counts()

NO ANSWER    8976
BUSY         6639
ANSWERED     6532
FAILED        363
Name: status, dtype: int64

In [19]:
df_call_record2 = df_call_record2.replace({'NO ANSWER': 'not_answered', 'BUSY': 'not_answered', 'ANSWERED': 'answered', 'FAILED': 'failed'})

In [20]:
# df_call_record2['hod_of_voicebot_connected'] = df_call_record1['call_duration'].apply(lambda x: pd.to_datetime(df_call_record2.start_time).dt.hour if x != '0' else 'NaN')

df_call_record2['hod_of_voicebot_connected'] = pd.to_datetime(df_call_record2.start_time).dt.hour
df_call_record2['date'] = pd.to_datetime(df_call_record2.start_time).dt.date
df_call_record2['dom_of_voicebot_connected'] = pd.to_datetime(df_call_record2.start_time).dt.day
df_call_record2['dow_of_voicebot_connected'] = pd.to_datetime(df_call_record2.start_time).dt.dayofweek
df_call_record2['date_time'] = pd.to_datetime(df_call_record2.start_time)

In [21]:
df_call_record2['voicebot_triggered'] = df_call_record2['status'].apply(lambda x: '1' if x != '' else '0')
df_call_record2['voicebot_connected'] = df_call_record2['status'].apply(lambda x: '1' if x == 'answered' else '0')

In [22]:
df_call_record2 = df_call_record2.rename(columns={'call_duration': 'duration_of_voicebot_connected'})

In [23]:
df_call_record22 = df_call_record2[["phone_number", "date", "voicebot_triggered","voicebot_connected","duration_of_voicebot_connected","hod_of_voicebot_connected","dow_of_voicebot_connected","dom_of_voicebot_connected"]]

In [24]:
df_call_record22

,phone_number,date,voicebot_triggered,voicebot_connected,duration_of_voicebot_connected,hod_of_voicebot_connected,dow_of_voicebot_connected,dom_of_voicebot_connected
0,8528846901,2021-12-21,1,0,0,17,1,21
1,8769132151,2021-12-21,1,0,0,17,1,21
2,9414604647,2021-12-21,1,0,0,17,1,21
3,9099463658,2021-12-21,1,0,0,17,1,21
4,9879874368,2021-12-21,1,0,0,17,1,21
...,...,...,...,...,...,...,...,...
22505,9991716345,2021-12-20,1,1,43,17,0,20
22506,8299537878,2021-12-20,1,1,51,17,0,20
22507,7419003969,2021-12-20,1,1,57,17,0,20
22508,7906796524,2021-12-20,1,1,56,17,0,20
22509,9616412840,2021-12-20,1,1,114,17,0,20

In [25]:
df_call_record11

,phone_number,date,voicebot_triggered,voicebot_connected,duration_of_voicebot_connected,hod_of_voicebot_connected,dow_of_voicebot_connected,dom_of_voicebot_connected
0,9844481461,2021-09-08,1,1,4.0,17,2,8
1,9818381771,2021-09-08,1,1,16.0,17,2,8
2,9908486774,2021-09-08,1,0,0.0,17,2,8
3,9311852510,2021-09-08,1,0,0.0,17,2,8
4,9991207863,2021-09-08,1,1,15.0,17,2,8
...,...,...,...,...,...,...,...,...
576155,6201901687,2021-12-19,1,1,1.0,13,6,19
576156,9985221617,2021-12-30,1,1,6.0,15,3,30
576157,9910224095,2021-12-31,1,1,5.0,13,4,31
576158,9959248941,2022-01-01,1,1,5.0,12,5,1
576159,9910224095,2022-01-01,1,1,3.0,12,5,1

In [26]:
frames = [df_call_record11, df_call_record22]

df_call_record_final = pd.concat(frames)

In [27]:
df_call_record_final

,phone_number,date,voicebot_triggered,voicebot_connected,duration_of_voicebot_connected,hod_of_voicebot_connected,dow_of_voicebot_connected,dom_of_voicebot_connected
0,9844481461,2021-09-08,1,1,4.0,17,2,8
1,9818381771,2021-09-08,1,1,16.0,17,2,8
2,9908486774,2021-09-08,1,0,0.0,17,2,8
3,9311852510,2021-09-08,1,0,0.0,17,2,8
4,9991207863,2021-09-08,1,1,15.0,17,2,8
...,...,...,...,...,...,...,...,...
22505,9991716345,2021-12-20,1,1,43.0,17,0,20
22506,8299537878,2021-12-20,1,1,51.0,17,0,20
22507,7419003969,2021-12-20,1,1,57.0,17,0,20
22508,7906796524,2021-12-20,1,1,56.0,17,0,20
22509,9616412840,2021-12-20,1,1,114.0,17,0,20

In [28]:
df_call_record_final.to_csv('IVR_final.csv')

In [29]:
import json
import psycopg2
import psycopg2
import os

In [30]:
# conn = psycopg2.connect(database = 'recovery_service_db',
#                         user = 'piyush_read',
#                         password = 'fvhjdffegjd2wcddc',
#                         host = 'prod-recovery-read.cnzlch7wyuxy.ap-south-1.rds.amazonaws.com',
#                         port = 5432)
# cursor = conn.cursor()

# conn = psycopg2.connect(database = 'data_science_db',
#                         user = 'piyush',
#                         password = 'hgfdhghgdejfdh',
#                         host = 'data-sciteam.cnzlch7wyuxy.ap-south-1.rds.amazonaws.com',
#                         port = 5432)
# cursor = conn.cursor()

param_dic = {
    "host"      : "prod-recovery-read.cnzlch7wyuxy.ap-south-1.rds.amazonaws.com",
    "database"  : "data_science_db",
    "user"      : "piyush",
    "password"  : "fvhjdffegjd2wcddc"
}

In [31]:
csv_file = "IVR_final.csv"
df = pd.read_csv(csv_file)

In [30]:
def connect(params_dic):
    """ Connect to the PostgreSQL database server """
    conn = None
    try:
        # connect to the PostgreSQL server
        print('Connecting to the PostgreSQL database...')
        conn = psycopg2.connect(**params_dic)
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        sys.exit(1) 
    print("Connection successful")
    return conn

In [31]:
def copy_from_file(conn, df, table):
    """
    Here we are going save the dataframe on disk as 
    a csv file, load the csv file  
    and use copy_from() to copy it to the table
    """
    # Save the dataframe to disk
    tmp_df = "IVR_final.csv"
    df.to_csv(tmp_df, index_label='id', header=False)
    f = open(tmp_df, 'r')
    cursor = conn.cursor()
    try:
        cursor.copy_from(f, table, sep=",")
        conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        os.remove(tmp_df)
        print("Error: %s" % error)
        conn.rollback()
        cursor.close()
        return 1
    print("copy_from_file() done")
    cursor.close()
    os.remove(tmp_df)

In [33]:
conn = connect(params_dic) # connect to the database
copy_from_file(conn, df, 'df_call_record_final') # copy the dataframe to SQL
conn.close() # close the connection

NameError: name 'params_dic' is not defined