In [109]:
import os
import sys
import csv
import glob
import pandas as pd
path = r'/Users/AarshDayal/Downloads'
csv_files = glob.glob(os.path.join(path+'/September_2021', "*.csv"))

In [110]:
csv_files

['/Users/AarshDayal/Downloads/September_2021/x1627042829969_61683196ce82a47bde0f68c8_figmps2h.csv',
 '/Users/AarshDayal/Downloads/September_2021/x1627042829969_617115431bff870012d24cf0_ots1vj6x.csv',
 '/Users/AarshDayal/Downloads/September_2021/x1627042829969_616d250a56071d5a75374501_sminkip7.csv',
 '/Users/AarshDayal/Downloads/September_2021/5S_x1627042829969_20.09-Bucket-X.B-zm.csv',
 '/Users/AarshDayal/Downloads/September_2021/Fu_x1627042829969_13.09-Bucket-X.W-zm.csv',
 '/Users/AarshDayal/Downloads/September_2021/IK_x1627042829969_6.09-check.csv',
 '/Users/AarshDayal/Downloads/September_2021/R6_x1627042829969_18.09-Bucket-X.W-zm.csv',
 '/Users/AarshDayal/Downloads/September_2021/x1627042829969_61727f0543d44100121ccda9_mndm94tz.csv',
 '/Users/AarshDayal/Downloads/September_2021/x1627042829969_616d2ac613295e85bcb684ec_c8c92sdk.csv',
 '/Users/AarshDayal/Downloads/September_2021/83_x1627042829969_17.09-Bucket-X.W-zm-retry.csv',
 '/Users/AarshDayal/Downloads/September_2021/ez_x1627042829969_16.09-Bucket-X.W-zm.csv',
 '/Users/AarshDayal/Downloads/September_2021/rU_x1627042829969_17.09-Bucket-X.W.A-zm.csv',
 '/Users/AarshDayal/Downloads/September_2021/Whataap-Nov-2021.csv',
 '/Users/AarshDayal/Downloads/September_2021/Js_x1627042829969_9.9-NC-zm.csv',
 '/Users/AarshDayal/Downloads/September_2021/7O_x1627042829969_21.09-Bucket-X.W-zm.csv',
 '/Users/AarshDayal/Downloads/September_2021/x1627042829969_616a7dd63e6df9164c0f9af9_li68hqe6.csv',
 '/Users/AarshDayal/Downloads/September_2021/yL_x1627042829969_15.09-Bucket-X.W-zm.csv',
 '/Users/AarshDayal/Downloads/September_2021/x1627042829969_6156c615efb88cfb4faa43a9_82d8pdiv.csv',
 '/Users/AarshDayal/Downloads/September_2021/x1627042829969_615ab20a7b8f3bec89207b66_xyf7c20u.csv',
 '/Users/AarshDayal/Downloads/September_2021/x1627042829969_61769457ad225900126abdee_h8ud3a1w.csv',
 '/Users/AarshDayal/Downloads/September_2021/Whataap-Dec.csv',
 '/Users/AarshDayal/Downloads/September_2021/H0_x1627042829969_17.09-Bucket-X.W.A-zm.csv',
 '/Users/AarshDayal/Downloads/September_2021/rz_x1627042829969_23.09-MasterBucket.W-zm.csv',
 '/Users/AarshDayal/Downloads/September_2021/x1627042829969_616e7ca6d75c5b00138ca664_jocm0sm2.csv',
 '/Users/AarshDayal/Downloads/September_2021/x1627042829969_617015f2346d9d0014412cc3_vezpkr7t.csv',
 '/Users/AarshDayal/Downloads/September_2021/r6_x1627042829969_14.09-Bucket-X.W-zm.csv',
 '/Users/AarshDayal/Downloads/September_2021/LE_x1627042829969_16-8,-Bucket-X.csv',
 '/Users/AarshDayal/Downloads/September_2021/Fq_x1627042829969_2.09-test-2.0.csv',
 '/Users/AarshDayal/Downloads/September_2021/kb_x1627042829969_24.09-Master-bucket-WA-zm.csv',
 '/Users/AarshDayal/Downloads/September_2021/gQ_x1627042829969_6.09-check.csv',
 '/Users/AarshDayal/Downloads/September_2021/x1627042829969_616ad8f4fcaca671b26b01d1_5b7puxke.csv']

In [111]:
df_whatsapp = pd.DataFrame()

In [112]:
for f in csv_files:
    # read the csv file
    print(f)
    temp_df_wa = pd.read_csv(f)
    df_whatsapp = pd.concat([df_whatsapp, temp_df_wa],axis=0 )

/Users/AarshDayal/Downloads/September_2021/x1627042829969_61683196ce82a47bde0f68c8_figmps2h.csv
/Users/AarshDayal/Downloads/September_2021/x1627042829969_617115431bff870012d24cf0_ots1vj6x.csv
/Users/AarshDayal/Downloads/September_2021/x1627042829969_616d250a56071d5a75374501_sminkip7.csv
/Users/AarshDayal/Downloads/September_2021/5S_x1627042829969_20.09-Bucket-X.B-zm.csv
/Users/AarshDayal/Downloads/September_2021/Fu_x1627042829969_13.09-Bucket-X.W-zm.csv
/Users/AarshDayal/Downloads/September_2021/IK_x1627042829969_6.09-check.csv
/Users/AarshDayal/Downloads/September_2021/R6_x1627042829969_18.09-Bucket-X.W-zm.csv
/Users/AarshDayal/Downloads/September_2021/x1627042829969_61727f0543d44100121ccda9_mndm94tz.csv
/Users/AarshDayal/Downloads/September_2021/x1627042829969_616d2ac613295e85bcb684ec_c8c92sdk.csv
/Users/AarshDayal/Downloads/September_2021/83_x1627042829969_17.09-Bucket-X.W-zm-retry.csv
/Users/AarshDayal/Downloads/September_2021/ez_x1627042829969_16.09-Bucket-X.W-zm.csv
/Users/AarshDayal/Downloads/September_2021/rU_x1627042829969_17.09-Bucket-X.W.A-zm.csv
/Users/AarshDayal/Downloads/September_2021/Whataap-Nov-2021.csv
/Users/AarshDayal/Downloads/September_2021/Js_x1627042829969_9.9-NC-zm.csv
/Users/AarshDayal/Downloads/September_2021/7O_x1627042829969_21.09-Bucket-X.W-zm.csv
/Users/AarshDayal/Downloads/September_2021/x1627042829969_616a7dd63e6df9164c0f9af9_li68hqe6.csv
/Users/AarshDayal/Downloads/September_2021/yL_x1627042829969_15.09-Bucket-X.W-zm.csv
/Users/AarshDayal/Downloads/September_2021/x1627042829969_6156c615efb88cfb4faa43a9_82d8pdiv.csv
/Users/AarshDayal/Downloads/September_2021/x1627042829969_615ab20a7b8f3bec89207b66_xyf7c20u.csv
/Users/AarshDayal/Downloads/September_2021/x1627042829969_61769457ad225900126abdee_h8ud3a1w.csv
/Users/AarshDayal/Downloads/September_2021/Whataap-Dec.csv
/Users/AarshDayal/Downloads/September_2021/H0_x1627042829969_17.09-Bucket-X.W.A-zm.csv
/Users/AarshDayal/Downloads/September_2021/rz_x1627042829969_23.09-MasterBucket.W-zm.csv
/Users/AarshDayal/Downloads/September_2021/x1627042829969_616e7ca6d75c5b00138ca664_jocm0sm2.csv
/Users/AarshDayal/Downloads/September_2021/x1627042829969_617015f2346d9d0014412cc3_vezpkr7t.csv
/Users/AarshDayal/Downloads/September_2021/r6_x1627042829969_14.09-Bucket-X.W-zm.csv
/Users/AarshDayal/Downloads/September_2021/LE_x1627042829969_16-8,-Bucket-X.csv
/Users/AarshDayal/Downloads/September_2021/Fq_x1627042829969_2.09-test-2.0.csv
/Users/AarshDayal/Downloads/September_2021/kb_x1627042829969_24.09-Master-bucket-WA-zm.csv
/Users/AarshDayal/Downloads/September_2021/gQ_x1627042829969_6.09-check.csv
/Users/AarshDayal/Downloads/September_2021/x1627042829969_616ad8f4fcaca671b26b01d1_5b7puxke.csv

In [113]:
df_whatsapp.columns

Index(['CampaignId', 'Campaign Name', 'BotId', 'UserId', 'User Details',
       'Template ID', 'Channel', 'Sender ID', 'Status', 'Comments',
       'Sent Time', 'Delivered Time', 'Read Time', 'Scheduled Time',
       'Error Resolution'],
      dtype='object')

In [114]:
import json

In [115]:
def clean_json(x):
    "Create apply function for decoding JSON"
    return json.loads(x)

In [116]:
df_whatsapp['User_Details'] = df_whatsapp['User Details'].apply(clean_json)
user_details = df_whatsapp['User_Details'].values.tolist()
df_whatsapp_details = pd.json_normalize(user_details)
df_whatsapp_new = pd.concat([df_whatsapp.reset_index(),df_whatsapp_details],axis=1)
df_whatsapp_new['phone_number']= df_whatsapp_new['number'].apply(lambda x: int(str(x)[-10:]))
df_whatsapp_new = df_whatsapp_new.rename(columns={'UserId': 'Phone'})
df_whatsapp_new.head()

,index,CampaignId,Campaign Name,BotId,Phone,User Details,Template ID,Channel,Sender ID,Status,...,due_amounts,manual_payment_link,lender_name,audienceId,helpline_number,delay_reason,total_conversations,payment_status,payment_link_status,phone_number
0,0,61683196ce82a47bde0f68c8,NaN,x1627042829969,9.188942e+11,"{""name"":""Jyoti thakur"",""tags"":[""ZEST_14-10""],""...",payment_link1,whatsapp,9.174830e+11,failed,...,7431,https://rzp.io/i/LDXWcqcrx,Aditya Birla,60fab66f6dfe71538b0a8e17,NaN,NaN,NaN,NaN,NaN,8894190346
1,1,61683196ce82a47bde0f68c8,NaN,x1627042829969,9.188477e+11,"{""name"":""Vijay kumar"",""tags"":[""ZEST_14-10""],""n...",payment_link1,whatsapp,9.174830e+11,failed,...,4367,https://rzp.io/i/gZ9ykWKcy,GhallaBhansali,60fab66f6dfe71538b0a8e17,NaN,NaN,NaN,NaN,NaN,8847682695
2,2,61683196ce82a47bde0f68c8,NaN,x1627042829969,9.196762e+11,"{""name"":""Ankit Bhatt"",""tags"":[""ZEST_14-10""],""n...",payment_link1,whatsapp,9.174830e+11,failed,...,12002,https://rzp.io/i/UQXPk0PSeu,CreditSaison,60fab66f6dfe71538b0a8e17,NaN,NaN,NaN,NaN,NaN,9676168051
3,3,61683196ce82a47bde0f68c8,NaN,x1627042829969,9.186889e+11,"{""name"":""P Rajasekhar"",""tags"":[""ZEST_14-10""],""...",payment_link1,whatsapp,9.174830e+11,failed,...,7431,#N/A,GhallaBhansali,60fab66f6dfe71538b0a8e17,NaN,NaN,NaN,NaN,NaN,8688884202
4,4,61683196ce82a47bde0f68c8,NaN,x1627042829969,9.180767e+11,"{""name"":""UZMA QURESHI"",""tags"":[""ZEST_14-10""],""...",payment_link1,whatsapp,9.174830e+11,failed,...,9609,https://rzp.io/i/Guz5Oq5St,GhallaBhansali,60fab66f6dfe71538b0a8e17,NaN,NaN,NaN,NaN,NaN,8076682249

In [117]:
df_whatsapp_new = df_whatsapp_new.rename(columns={'Read Time': 'Read_Time','Sent Time': 'Sent_Time'})

In [118]:
df_whatsapp_new['wa_triggered'] = df_whatsapp_new['CampaignId'].apply(lambda x: '1' if x != '' else '0')

In [119]:
df_whatsapp_new['wa_delivered'] = df_whatsapp_new['Status'].apply(lambda x: '1' if x == 'delivered' else '0')

In [120]:
df_whatsapp_new['wa_read'] = df_whatsapp_new['Status'].apply(lambda x: '1' if x == 'read' else '0')

In [121]:
df_whatsapp_new['Read_Time'] = pd.to_datetime(df_whatsapp_new['Read_Time'],errors='coerce')

In [122]:
df_whatsapp_new['hour_of_day_read_time'] = pd.to_datetime(df_whatsapp_new.Read_Time).dt.hour
df_whatsapp_new['date'] = pd.to_datetime(df_whatsapp_new.Sent_Time).dt.date
df_whatsapp_new['dow_wa_read_time'] = pd.to_datetime(df_whatsapp_new.Read_Time).dt.dayofweek
df_whatsapp_new['dom_wa_read_time'] = pd.to_datetime(df_whatsapp_new.Read_Time).dt.day

In [123]:
df_whatsapp_new.head()

,index,CampaignId,Campaign Name,BotId,Phone,User Details,Template ID,Channel,Sender ID,Status,...,payment_status,payment_link_status,phone_number,wa_triggered,wa_delivered,wa_read,hour_of_day_read_time,date,dow_wa_read_time,dom_wa_read_time
0,0,61683196ce82a47bde0f68c8,NaN,x1627042829969,9.188942e+11,"{""name"":""Jyoti thakur"",""tags"":[""ZEST_14-10""],""...",payment_link1,whatsapp,9.174830e+11,failed,...,NaN,NaN,8894190346,1,0,0,NaN,2021-10-14,NaN,NaN
1,1,61683196ce82a47bde0f68c8,NaN,x1627042829969,9.188477e+11,"{""name"":""Vijay kumar"",""tags"":[""ZEST_14-10""],""n...",payment_link1,whatsapp,9.174830e+11,failed,...,NaN,NaN,8847682695,1,0,0,NaN,2021-10-14,NaN,NaN
2,2,61683196ce82a47bde0f68c8,NaN,x1627042829969,9.196762e+11,"{""name"":""Ankit Bhatt"",""tags"":[""ZEST_14-10""],""n...",payment_link1,whatsapp,9.174830e+11,failed,...,NaN,NaN,9676168051,1,0,0,NaN,2021-10-14,NaN,NaN
3,3,61683196ce82a47bde0f68c8,NaN,x1627042829969,9.186889e+11,"{""name"":""P Rajasekhar"",""tags"":[""ZEST_14-10""],""...",payment_link1,whatsapp,9.174830e+11,failed,...,NaN,NaN,8688884202,1,0,0,NaN,2021-10-14,NaN,NaN
4,4,61683196ce82a47bde0f68c8,NaN,x1627042829969,9.180767e+11,"{""name"":""UZMA QURESHI"",""tags"":[""ZEST_14-10""],""...",payment_link1,whatsapp,9.174830e+11,failed,...,NaN,NaN,8076682249,1,0,0,NaN,2021-10-14,NaN,NaN

In [124]:
#df_whatsapp_new = df_whatsapp_new[[1,2,3,6,7,11,29,30,31,32,33,34,35,3620,21,22,23,24,25,26]]
# df_whatsapp_new1 = df_whatsapp_new.drop(df_whatsapp_new.columns[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]], axis=1) 
#df_whatsapp_new.drop(df_whatsapp_new.columns[[0,1,3]], axis=1, inplace=True)
df_whatsapp_new1 = df_whatsapp_new[["phone_number", "date", "wa_triggered","wa_delivered","wa_read","hour_of_day_read_time","dow_wa_read_time","dom_wa_read_time"]]
df_whatsapp_new1

,phone_number,date,wa_triggered,wa_delivered,wa_read,hour_of_day_read_time,dow_wa_read_time,dom_wa_read_time
0,8894190346,2021-10-14,1,0,0,NaN,NaN,NaN
1,8847682695,2021-10-14,1,0,0,NaN,NaN,NaN
2,9676168051,2021-10-14,1,0,0,NaN,NaN,NaN
3,8688884202,2021-10-14,1,0,0,NaN,NaN,NaN
4,8076682249,2021-10-14,1,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
381773,7010424084,2021-10-16,1,0,1,19.0,5.0,6.0
381774,9315582253,2021-10-16,1,0,1,14.0,6.0,17.0
381775,9847731718,2021-10-16,1,0,1,21.0,5.0,16.0
381776,7603010830,2021-10-16,1,0,1,21.0,5.0,16.0
381777,8779844070,2021-10-16,1,0,0,NaN,NaN,NaN

In [125]:
df_whatsapp_new1 = df_whatsapp_new1.groupby('date').count()
df_whatsapp_new1

,phone_number,wa_triggered,wa_delivered,wa_read,hour_of_day_read_time,dow_wa_read_time,dom_wa_read_time
date,,,,,,,
2021-08-16,8591,8591,8591,8591,6493,6493,6493
2021-09-02,2,2,2,2,0,0,0
2021-09-06,4,4,4,4,0,0,0
2021-09-09,1039,1039,1039,1039,508,508,508
2021-09-13,18124,18124,18124,18124,9676,9676,9676
2021-09-14,17046,17046,17046,17046,811,811,811
2021-09-15,16245,16245,16245,16245,9868,9868,9868
2021-09-16,14593,14593,14593,14593,9709,9709,9709
2021-09-17,42432,42432,42432,42432,832,832,832
2021-09-18,13645,13645,13645,13645,9735,9735,9735
2021-09-19,5506,5506,5506,5506,93,93,93
2021-09-20,14695,14695,14695,14695,9444,9444,9444
2021-09-21,13935,13935,13935,13935,9230,9230,9230
2021-09-23,11132,11132,11132,11132,6110,6110,6110
2021-09-24,11014,11014,11014,11014,5911,5911,5911
2021-10-01,4502,4502,4502,4502,2654,2654,2654
2021-10-04,4049,4049,4049,4049,2573,2573,2573
2021-10-14,23637,23637,23637,23637,0,0,0
2021-10-16,29677,29677,29677,29677,10092,10092,10092
2021-10-18,29055,29055,29055,29055,9455,9455,9455
2021-10-19,18831,18831,18831,18831,9575,9575,9575
2021-10-20,5003,5003,5003,5003,3338,3338,3338
2021-10-21,4902,4902,4902,4902,3616,3616,3616
2021-10-22,5002,5002,5002,5002,3549,3549,3549
2021-10-25,5002,5002,5002,5002,3242,3242,3242
2021-11-01,6286,6286,6286,6286,4124,4124,4124
2021-11-02,6226,6226,6226,6226,4001,4001,4001
2021-11-06,5178,5178,5178,5178,2963,2963,2963
2021-11-08,4873,4873,4873,4873,2907,2907,2907
2021-11-09,5628,5628,5628,5628,3232,3232,3232
2021-11-13,4389,4389,4389,4389,3112,3112,3112
2021-11-15,3984,3984,3984,3984,2671,2671,2671
2021-11-17,3721,3721,3721,3721,2432,2432,2432
2021-11-18,3592,3592,3592,3592,2260,2260,2260
2021-11-19,3486,3486,3486,3486,2048,2048,2048
2021-11-20,3390,3390,3390,3390,1961,1961,1961
2021-11-22,3264,3264,3264,3264,1813,1813,1813
2021-11-23,3195,3195,3195,3195,1546,1546,1546
2021-12-11,1247,1247,1247,1247,807,807,807
2021-12-13,927,927,927,927,534,534,534
2021-12-14,861,861,861,861,440,440,440
2021-12-15,798,798,798,798,420,420,420
2021-12-16,947,947,947,947,487,487,487
2021-12-17,734,734,734,734,360,360,360
2021-12-18,706,706,706,706,353,353,353
2021-12-20,683,683,683,683,354,354,354

In [126]:
df_whatsapp_new1.to_csv('whatsapp_new.csv')